spring:
  profiles: production

  datasource:
    url: jdbc:mariadb:// <url> : <port> / <db-name>
    driver-class-name: org.mariadb.jdbc.Driver
    username: <username>
    password: <password>
    continue-on-error: true
    initialize: false
    test-on-borrow: true
    validation-query: SELECT 1
    max-active: 5

  jpa:
    database-platform: MYSQL
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: <server-port>